alert('Кто разработал язык программирования JavaScript?')
alert('Айк Брендан')
alert('За сколько дней был разработан JavaScript?')
alert('JavaScript был создан за 10 дней')
alert('В каком году появился JavaScript?')
alert('В 1995 году')
alert('JavaScript - это то же самое, что и Java?')
alert('JavaScript это Java')
alert('Как называется спецификация JavaScript?')
alert('JavaScript спецификация называется ECMAScript')